Will not work

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,20 +11,19 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout code
+      - nas -al build
+          file build/test_dummy
+          chmod +x build/test_dummy
+          ./build/test_dummy || echo "Test failed with exit code $?"
+me: Checkout code
         uses: actions/checkout@v4
 
-      - name: Install Protobuf 35
+      - name: Install dependencies
         run: |
-          sudo add-apt-repository ppa:protobuf/ppa -y
           sudo apt-get update
           sudo apt-get install -y \
-            protobuf-compiler libprotobuf-dev
-
-      - name: Install gRPC and build tools
-        run: |
-          sudo apt-get install -y \
             build-essential cmake pkg-config \
+            libprotobuf-dev protobuf-compiler \
             libgrpc++-dev protobuf-compiler-grpc
 
       - name: Remove old CMake cache
@@ -42,7 +41,4 @@ jobs:
       - name: Run tests
         run: |
           echo "Running test_dummy..."
-          ls -al build
-          file build/test_dummy
-          chmod +x build/test_dummy
-          ./build/test_dummy || echo "Test failed with exit code $?"
+          l
